const data = {
    concerts: [
        {
            year: 2019,
            semester: 'summer',
            dates: [
                '2019-07-18',
                '2019-07-20',
            ],
            time: '20:00',
            prices: {
                advance: {
                    reduced: 4.0,
                    regular: 7.0,
                },
                boxOffice: {
                    reduced: 5.0,
                    regular: 8.0,
                },
            },
            title: 'Jazznuts - Simsalasing',
            location: 'Audimax Regensburg',
            songs: [],
        },
        {
            year: 2018,
            semester: 'winter',
            dates: [
                '2019-01-31',
                '2019-02-01',
            ],
            time: '20:00',
            prices: {
                advance: {
                    reduced: 4.0,
                    regular: 7.0,
                },
                boxOffice: {
                    reduced: 5.0,
                    regular: 8.0,
                },
            },
            title: 'Jazznuts About time',
            location: 'Audimax Regensburg',
            songs: [
                'Dancing Queen',
                'History of Everything (The Big Bang Theory)',
                'Don\'t Stop Me Now',
                'September',
                'Back to the Future',
                'Rama Lama Ding Dong',
                'Man in the Mirror',
                'Chasing Cars',
                'Sixteen Tons',
                'Don\'t stop believing',
                'Yellow Submarine',
                'Radioactive',
                'You\'ve Got The Love',
                'Time After Time',
                'The Longest Time',
            ],
        },
        {
            year: 2018,
            semester: 'summer',
            dates: [
                '2018-06-28',
                '2018-06-30',
            ],
            time: '20:00',
            title: 'Jazznuts - Rockappella',
            location: 'Audimax Regensburg',
            songs: [
                'Alkohol',
                'I Love Rock’n’Roll',
                'Ironic',
                'Zombie',
                'Sweet Dreams',
                'Happy Together',
                'I Don’t Want To Miss A Thing',
                'Westerland',
                'Erlaube mir, feins Mädchen',
                'We Will Rock You',
                'Fußball - WM 2018',
                'Hysteria - I Want It Now',
                'Human',
                'Hard Rock Hallelujah',
            ],
        },
        {
            year: 2017,
            semester: 'winter',
            dates: [
                '2018-01-11',
                '2018-01-13',
            ],
            time: '20:00',
            title: 'Jazznuts im Wunderland',
            location: 'Audimax Regensburg',
            songs: [
                'Let me entertain you',
                'Übern See',
                'Royals',
                'Der König in Thule',
                'Shut up and dance',
                'Poison',
                'Paradise',
                'The colors of the wind',
                'Supercalifragilisticexpialigetisch',
                'Let It Go',
                'Donne',
                'Die Schöne und das Biest',
                'Bohemian Rhapsody',
                'Dream On',
            ],
        },
        {
            year: 2017,
            semester: 'summer',
            dates: [
                '2017-07-03',
                '2017-07-05',
            ],
            time: '20:00',
            title: 'Jazznuts - Sing\'n\'Swim',
            location: 'Audimax Regensburg',
            songs: [
                'Another Day of Sun',
                'Banana Boat Song',
                'How Far I’ll Go!',
                'Haus am See',
                'Tourdion',
                'Shut up and dance',
                'Sweet Dreams',
                'Sing',
                'Flashlight',
                'Perfekte Welle',
                'I get around',
                'Unter dem Meer',
                'Send My Love',
                'Baba Yetu',
                'Walking On Sunshine',
            ],
        },
        {
            year: 2016,
            semester: 'winter',
            dates: [
                '2017-01-12',
                '2017-01-13',
            ],
            time: '20:00',
            title: 'Jazznuts outta space',
            location: 'Audimax Regensburg',
            songs: [
                'Earth Song',
                'Major Tom',
                'Weit, Weit Weg',
                'My Way',
                'And So It Goes',
                'Coro dei Pompieri',
                'Falling Slowly',
                'Save the World / Don’t You Worry Child',
                'Don’t Stop Me Now',
                'Some Nights',
                'Gabriella’s Song',
                'The Sound of Silence',
                'Radioactive',
                'The Scientist',
            ],
        },
        {
            year: 2016,
            semester: 'summer',
            dates: [
                '2016-06-20',
                '2016-06-23',
            ],
            time: '20:00',
            title: 'Dschungelfieber',
            location: 'Audimax Regensburg',
            songs: [
                'Bohemian Rhapsody',
                'Uptown Funk',
                'Jamaica Farewell',
                'The Lion sleeps tonight', 
                'Baba Yetu',
                'Let it go',
                'You’ll be in my heart',
                'Siyahamba',
                'Ich wäre gern wie du',
                'Mamaliye',
                'Probier’s mal mit Gemütlichkeit',
                'Don’t stop believing',
                'I see fire',
                'Say something', 
                'Chor der Geier',
                'Can you feel the love tonight',
                'Hakuna Matata',
            ],
        },
        {
            year: 2015,
            semester: 'winter',
            dates: [
                '2015-12-17',
                '2015-12-18',
            ],
            time: '20:00',
            title: 'Jazznuts - Das Grusical',
            location: 'H24 Uni Regensburg',
            songs: [],
        },
    ],
};

module.exports = {
    data,
};
