const data = {
  concerts: [
    {
      year: 2024,
      semester: "summer",
      dates: ["2024-07-18 20:00", "2024-07-19 20:00"],
      prices: {
        advance: {
          reduced: 5.0,
          regular: 10.0,
        },
        boxOffice: {
          reduced: 7.0,
          regular: 12.0,
        },
      },
      title: "Jazznuts - Olympi-A-cappella",
      imageUrl: undefined,
      location: "Audimax Regensburg",
      songs: [
        "Paradise",
        "One moment in time",
        "Never gonna give you up",
        "We are the champions",
        "Run to you",
        "Hysteria",
        "Everglow",
        "Radioactive",
        "Shots",
        "Happy together",
        "You are the reason",
        "My way",
      ],
    },
    {
      year: 2023,
      semester: "winter",
      dates: ["2024-02-09 20:15", "2024-02-10 20:15"],
      prices: {
        advance: {
          reduced: 5.0,
          regular: 10.0,
        },
        boxOffice: {
          reduced: 7.0,
          regular: 12.0,
        },
      },
      title: "Jazznuts - A caBella Italia",
      imageUrl: "/posters/2023_WS_A_caBella_Italia.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Radio",
        "I knew you were trouble",
        "Laura non c’è",
        "My songs know what you did in the dark (Light em up)",
        "Übern See",
        "Beggin’",
        "Mamma mia!",
        "Poison",
        "Azzurro",
        "This is me",
        "Shallow",
        "September",
      ],
    },
    {
      year: 2023,
      semester: "summer",
      dates: ["2023-07-20 20:00", "2023-07-21 20:00"],
      prices: {
        advance: {
          reduced: 4.0,
          regular: 8.0,
        },
        boxOffice: {
          reduced: 5.0,
          regular: 10.0,
        },
      },
      title: "Jazznuts - Crime Time",
      imageUrl: "/posters/2023_SS_Crime_Time.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Welcome to the black parade",
        "I don’t want to miss a thing",
        "Coro dei pompieri",
        "The scientist",
        "Make you feel my love",
        "Haus am See",
        "Chandelier",
        "I want it that way",
        "Lullabye (Goodnight, my angel)",
        "Bohemian rhapsody",
        "Man in the mirror",
        "Just sing it!",
      ],
    },
    {
      year: 2022,
      semester: "winter",
      dates: ["2023-02-02 20:00", "2023-02-04 20:00"],
      prices: {
        advance: {
          reduced: 4.0,
          regular: 8.0,
        },
        boxOffice: {
          reduced: 5.0,
          regular: 10.0,
        },
      },
      title: "Jazznuts - Das Mystical",
      imageUrl: "/posters/2022_WS_Das_Mystical.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Smells like teen spirit",
        "Sweet dreams",
        "Chasing cars",
        "Engel",
        "Caresse sur l'océan",
        "Tage wie diese",
        "And so it goes",
        "Bicycle race",
        "Save the World / Don’t You Worry Child",
        "Nellie the elephant",
        "Dancing queen",
        "Hard rock hallelujah",
      ],
    },
    {
      year: 2022,
      semester: "summer",
      dates: ["2022-07-21 20:00", "2022-07-24 17:00"],
      prices: {
        advance: {
          reduced: 4.0,
          regular: 8.0,
        },
        boxOffice: {
          reduced: 5.0,
          regular: 9.0,
        },
      },
      title: "Jazznuts - The Show Must Go On!",
      imageUrl: "/posters/2022_SS_The_Show_Must_Go_On.jpg",
      location: "Audimax Regensburg",
      songs: [
        "This is me",
        "Run to you",
        "Set fire to the rain",
        "Ba-Ba-Banküberfall",
        "Wie kann es sein",
        "Bring me to life",
        "Zusammen",
        "Mambo",
        "Africa",
        "Hysteria",
        "The show must go on",
        "Baba yetu",
        "Flashlight",
      ],
    },
    {
      year: 2019,
      semester: "winter",
      dates: ["2020-01-16 20:00", "2020-01-17 20:00"],
      prices: {
        advance: {
          reduced: 4.0,
          regular: 8.0,
        },
        boxOffice: {
          reduced: 5.0,
          regular: 9.0,
        },
      },
      title: "Jazznuts - Go West",
      imageUrl: "/posters/2019_SS_Go_West.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Boondocks",
        "Somebody to Love",
        "Mädchen",
        "Sweet Home Alabama",
        "Alkohol",
        "Ring of Fire",
        "Mein kleiner grüner Kaktus",
        "Zieh die Schuh aus",
        "Wake Me Up",
        "Augenbling",
        "It’s My Life",
        "Can’t Help Falling in Love",
        "Drive My Car",
        "I Wish/Wild Wild West",
      ],
    },
    {
      year: 2019,
      semester: "summer",
      dates: ["2019-07-18 20:00", "2019-07-20 20:00"],
      prices: {
        advance: {
          reduced: 4.0,
          regular: 8.0,
        },
        boxOffice: {
          reduced: 5.0,
          regular: 9.0,
        },
      },
      title: "Jazznuts - Simsalasing",
      imageUrl: "/posters/2019_SS_Simsalasing.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Adventure of a lifetime",
        "Fix you",
        "A fire inside - Prelude 12/21",
        "The hanging tree",
        "Set fire to the rain",
        "The rains of castamere",
        "When you wish upon a star",
        "Superkalifragilistic",
        "I see fire",
        "Ich seh dich",
        "Ding-Dong! The witch is dead",
        "Baba yetu",
        "Take on me",
      ],
    },
    {
      year: 2018,
      semester: "winter",
      dates: ["2019-01-31 20:00", "2019-02-01 20:00"],
      prices: {
        advance: {
          reduced: 4.0,
          regular: 7.0,
        },
        boxOffice: {
          reduced: 5.0,
          regular: 8.0,
        },
      },
      title: "Jazznuts - About time",
      imageUrl: "/posters/2018_WS_About_Time.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Dancing Queen",
        "History of Everything (The Big Bang Theory)",
        "Don't Stop Me Now",
        "September",
        "Back to the Future",
        "Rama Lama Ding Dong",
        "Man in the Mirror",
        "Chasing Cars",
        "Sixteen Tons",
        "Don't stop believing",
        "Yellow Submarine",
        "Radioactive",
        "You've Got The Love",
        "Time After Time",
        "The Longest Time",
      ],
    },
    {
      year: 2018,
      semester: "summer",
      dates: ["2018-06-28 20:00", "2018-06-30 20:00"],
      title: "Jazznuts - Rockappella",
      imageUrl: "/posters/2018_SS_Rockappella.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Alkohol",
        "I Love Rock’n’Roll",
        "Ironic",
        "Zombie",
        "Sweet Dreams",
        "Happy Together",
        "I Don’t Want To Miss A Thing",
        "Westerland",
        "Erlaube mir, feins Mädchen",
        "We Will Rock You",
        "Fußball - WM 2018",
        "Hysteria - I Want It Now",
        "Human",
        "Hard Rock Hallelujah",
      ],
    },
    {
      year: 2017,
      semester: "winter",
      dates: ["2018-01-11 20:00", "2018-01-13 20:00"],
      title: "Jazznuts im Wunderland",
      imageUrl: "/posters/2017_WS_Jazznuts_im_Wunderland.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Let me entertain you",
        "Übern See",
        "Royals",
        "Der König in Thule",
        "Shut up and dance",
        "Poison",
        "Paradise",
        "The colors of the wind",
        "Supercalifragilisticexpialigetisch",
        "Let It Go",
        "Donne",
        "Die Schöne und das Biest",
        "Bohemian Rhapsody",
        "Dream On",
      ],
    },
    {
      year: 2017,
      semester: "summer",
      dates: ["2017-07-03 20:00", "2017-07-05 20:00"],
      title: "Jazznuts - Sing'n'Swim",
      imageUrl: "/posters/2017_SS_Sing_n_Swim.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Another Day of Sun",
        "Banana Boat Song",
        "How Far I’ll Go!",
        "Haus am See",
        "Tourdion",
        "Shut up and dance",
        "Sweet Dreams",
        "Sing",
        "Flashlight",
        "Perfekte Welle",
        "I get around",
        "Unter dem Meer",
        "Send My Love",
        "Baba Yetu",
        "Walking On Sunshine",
      ],
    },
    {
      year: 2016,
      semester: "winter",
      dates: ["2017-01-12 20:00", "2017-01-13 20:00"],
      title: "Jazznuts outta space",
      imageUrl: "/posters/2016_WS_Jazznuts_Outta_Space.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Earth Song",
        "Major Tom",
        "Weit, Weit Weg",
        "My Way",
        "And So It Goes",
        "Coro dei Pompieri",
        "Falling Slowly",
        "Save the World / Don’t You Worry Child",
        "Don’t Stop Me Now",
        "Some Nights",
        "Gabriella’s Song",
        "The Sound of Silence",
        "Radioactive",
        "The Scientist",
      ],
    },
    {
      year: 2016,
      semester: "summer",
      dates: ["2016-06-20 20:00", "2016-06-23 20:00"],
      title: "Dschungelfieber",
      imageUrl: "/posters/2016_SS_Dschungelfieber.jpg",
      location: "Audimax Regensburg",
      songs: [
        "Bohemian Rhapsody",
        "Uptown Funk",
        "Jamaica Farewell",
        "The Lion sleeps tonight",
        "Baba Yetu",
        "Let it go",
        "You’ll be in my heart",
        "Siyahamba",
        "Ich wäre gern wie du",
        "Mamaliye",
        "Probier’s mal mit Gemütlichkeit",
        "Don’t stop believing",
        "I see fire",
        "Say something",
        "Chor der Geier",
        "Can you feel the love tonight",
        "Hakuna Matata",
      ],
    },
    {
      year: 2015,
      semester: "winter",
      dates: ["2015-12-17 20:00", "2015-12-18 20:00"],
      title: "Jazznuts - Das Grusical",
      imageUrl: "/posters/2015_WS_Das_Grusical.jpg",
      location: "H24 Uni Regensburg",
      songs: [
        "Thriller",
        "Wahrheit",
        "Carpe Noctem",
        "Zombie",
        "Last Christmas",
        "Poison",
        "All I Ask of You",
        "The Time Warp",
        "Rocking Around the Christmas Tree",
        "Totale Finsternis",
        "The Music of the Night",
        "Engel",
        "Hark! The Herald Angels Sing",
        "Hard Rock Hallelujah",
        "The Phantom of the Opera",
        "Bring Me to Life",
      ],
    },
  ],
  general: {
    images: {
      logo: "https://stwno.de/images/Kultur/gallery/reg-jazznuts/4-jazznuts-logo.jpg",
      choir: "/Jazznuts_choir.jpg",
    },
    online: {
      website: {
        label: "www.jazznuts.de",
        url: "https://www.jazznuts.de",
      },
      reservation: {
        label: "Jetzt online reservieren",
        url: "https://www.jazznuts.de",
      },
      instagram: {
        label: "@jazznuts.regensburg",
        url: "https://www.instagram.com/jazznuts.regensburg",
      },
      facebook: {
        label: "@jazznuts",
        url: "https://www.facebook.com/jazznuts",
      },
    },
  },
};

module.exports = {
  data,
};
